create table
  public.potions (
    red integer null default 0,
    green integer null default 0,
    blue integer null default 0,
    dark integer null default 0,
    quantity integer null default 0,
    cost integer null default 50,
    id integer generated by default as identity,
    name text null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;